/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by Kubeform. DO NOT EDIT.

package v1alpha1

import (
	base "kubeform.dev/kubeform/apis/base/v1alpha1"

	core "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +k8s:openapi-gen=true
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`

type ExpressRouteCircuit struct {
	metav1.TypeMeta   `json:",inline,omitempty"`
	metav1.ObjectMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
	Spec              ExpressRouteCircuitSpec   `json:"spec,omitempty" protobuf:"bytes,2,opt,name=spec"`
	Status            ExpressRouteCircuitStatus `json:"status,omitempty" protobuf:"bytes,3,opt,name=status"`
}

type ExpressRouteCircuitSpecSku struct {
	Family string `json:"family" tf:"family" protobuf:"bytes,1,opt,name=family"`
	Tier   string `json:"tier" tf:"tier" protobuf:"bytes,2,opt,name=tier"`
}

type ExpressRouteCircuitSpec struct {
	ProviderRef core.LocalObjectReference `json:"providerRef" tf:"-" protobuf:"bytes,1,opt,name=providerRef"`

	ID string `json:"id,omitempty" tf:"id,omitempty" protobuf:"bytes,2,opt,name=id"`

	SecretRef *core.LocalObjectReference `json:"secretRef,omitempty" tf:"-" protobuf:"bytes,3,opt,name=secretRef"`

	// +optional
	AllowClassicOperations bool   `json:"allowClassicOperations,omitempty" tf:"allow_classic_operations,omitempty" protobuf:"varint,4,opt,name=allowClassicOperations"`
	BandwidthInMbps        int64  `json:"bandwidthInMbps" tf:"bandwidth_in_mbps" protobuf:"varint,5,opt,name=bandwidthInMbps"`
	Location               string `json:"location" tf:"location" protobuf:"bytes,6,opt,name=location"`
	Name                   string `json:"name" tf:"name" protobuf:"bytes,7,opt,name=name"`
	PeeringLocation        string `json:"peeringLocation" tf:"peering_location" protobuf:"bytes,8,opt,name=peeringLocation"`
	ResourceGroupName      string `json:"resourceGroupName" tf:"resource_group_name" protobuf:"bytes,9,opt,name=resourceGroupName"`
	// +optional
	ServiceKey          string `json:"-" sensitive:"true" tf:"service_key,omitempty"`
	ServiceProviderName string `json:"serviceProviderName" tf:"service_provider_name" protobuf:"bytes,10,opt,name=serviceProviderName"`
	// +optional
	ServiceProviderProvisioningState string `json:"serviceProviderProvisioningState,omitempty" tf:"service_provider_provisioning_state,omitempty" protobuf:"bytes,11,opt,name=serviceProviderProvisioningState"`
	// +kubebuilder:validation:MaxItems=1
	Sku []ExpressRouteCircuitSpecSku `json:"sku" tf:"sku" protobuf:"bytes,12,rep,name=sku"`
	// +optional
	Tags map[string]string `json:"tags,omitempty" tf:"tags,omitempty" protobuf:"bytes,13,rep,name=tags"`
}

type ExpressRouteCircuitStatus struct {
	// Resource generation, which is updated on mutation by the API Server.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty" protobuf:"varint,1,opt,name=observedGeneration"`
	// +optional
	Output *ExpressRouteCircuitSpec `json:"output,omitempty" protobuf:"bytes,2,opt,name=output"`
	// +optional
	State *base.State `json:"state,omitempty" protobuf:"bytes,3,opt,name=state"`
	// +optional
	Phase base.Phase `json:"phase,omitempty" protobuf:"bytes,4,opt,name=phase,casttype=kubeform.dev/kubeform/apis/base/v1alpha1.Phase"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true

// ExpressRouteCircuitList is a list of ExpressRouteCircuits
type ExpressRouteCircuitList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
	// Items is a list of ExpressRouteCircuit CRD objects
	Items []ExpressRouteCircuit `json:"items,omitempty" protobuf:"bytes,2,rep,name=items"`
}
