/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by Kubeform. DO NOT EDIT.

package v1alpha1

import (
	base "kubeform.dev/kubeform/apis/base/v1alpha1"

	core "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +k8s:openapi-gen=true
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`

type MonitorActionGroup struct {
	metav1.TypeMeta   `json:",inline,omitempty"`
	metav1.ObjectMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
	Spec              MonitorActionGroupSpec   `json:"spec,omitempty" protobuf:"bytes,2,opt,name=spec"`
	Status            MonitorActionGroupStatus `json:"status,omitempty" protobuf:"bytes,3,opt,name=status"`
}

type MonitorActionGroupSpecEmailReceiver struct {
	EmailAddress string `json:"emailAddress" tf:"email_address" protobuf:"bytes,1,opt,name=emailAddress"`
	Name         string `json:"name" tf:"name" protobuf:"bytes,2,opt,name=name"`
}

type MonitorActionGroupSpecSmsReceiver struct {
	CountryCode string `json:"countryCode" tf:"country_code" protobuf:"bytes,1,opt,name=countryCode"`
	Name        string `json:"name" tf:"name" protobuf:"bytes,2,opt,name=name"`
	PhoneNumber string `json:"phoneNumber" tf:"phone_number" protobuf:"bytes,3,opt,name=phoneNumber"`
}

type MonitorActionGroupSpecWebhookReceiver struct {
	Name       string `json:"name" tf:"name" protobuf:"bytes,1,opt,name=name"`
	ServiceURI string `json:"serviceURI" tf:"service_uri" protobuf:"bytes,2,opt,name=serviceURI"`
}

type MonitorActionGroupSpec struct {
	ProviderRef core.LocalObjectReference `json:"providerRef" tf:"-" protobuf:"bytes,1,opt,name=providerRef"`

	ID string `json:"id,omitempty" tf:"id,omitempty" protobuf:"bytes,2,opt,name=id"`

	// +optional
	EmailReceiver []MonitorActionGroupSpecEmailReceiver `json:"emailReceiver,omitempty" tf:"email_receiver,omitempty" protobuf:"bytes,3,rep,name=emailReceiver"`
	// +optional
	Enabled           bool   `json:"enabled,omitempty" tf:"enabled,omitempty" protobuf:"varint,4,opt,name=enabled"`
	Name              string `json:"name" tf:"name" protobuf:"bytes,5,opt,name=name"`
	ResourceGroupName string `json:"resourceGroupName" tf:"resource_group_name" protobuf:"bytes,6,opt,name=resourceGroupName"`
	ShortName         string `json:"shortName" tf:"short_name" protobuf:"bytes,7,opt,name=shortName"`
	// +optional
	SmsReceiver []MonitorActionGroupSpecSmsReceiver `json:"smsReceiver,omitempty" tf:"sms_receiver,omitempty" protobuf:"bytes,8,rep,name=smsReceiver"`
	// +optional
	Tags map[string]string `json:"tags,omitempty" tf:"tags,omitempty" protobuf:"bytes,9,rep,name=tags"`
	// +optional
	WebhookReceiver []MonitorActionGroupSpecWebhookReceiver `json:"webhookReceiver,omitempty" tf:"webhook_receiver,omitempty" protobuf:"bytes,10,rep,name=webhookReceiver"`
}

type MonitorActionGroupStatus struct {
	// Resource generation, which is updated on mutation by the API Server.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty" protobuf:"varint,1,opt,name=observedGeneration"`
	// +optional
	Output *MonitorActionGroupSpec `json:"output,omitempty" protobuf:"bytes,2,opt,name=output"`
	// +optional
	State *base.State `json:"state,omitempty" protobuf:"bytes,3,opt,name=state"`
	// +optional
	Phase base.Phase `json:"phase,omitempty" protobuf:"bytes,4,opt,name=phase,casttype=kubeform.dev/kubeform/apis/base/v1alpha1.Phase"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true

// MonitorActionGroupList is a list of MonitorActionGroups
type MonitorActionGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
	// Items is a list of MonitorActionGroup CRD objects
	Items []MonitorActionGroup `json:"items,omitempty" protobuf:"bytes,2,rep,name=items"`
}
