/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by Kubeform. DO NOT EDIT.

package v1alpha1

import (
	base "kubeform.dev/kubeform/apis/base/v1alpha1"

	core "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +k8s:openapi-gen=true
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`

type MonitorAutoscaleSetting struct {
	metav1.TypeMeta   `json:",inline,omitempty"`
	metav1.ObjectMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
	Spec              MonitorAutoscaleSettingSpec   `json:"spec,omitempty" protobuf:"bytes,2,opt,name=spec"`
	Status            MonitorAutoscaleSettingStatus `json:"status,omitempty" protobuf:"bytes,3,opt,name=status"`
}

type MonitorAutoscaleSettingSpecNotificationEmail struct {
	// +optional
	CustomEmails []string `json:"customEmails,omitempty" tf:"custom_emails,omitempty" protobuf:"bytes,1,rep,name=customEmails"`
	// +optional
	SendToSubscriptionAdministrator bool `json:"sendToSubscriptionAdministrator,omitempty" tf:"send_to_subscription_administrator,omitempty" protobuf:"varint,2,opt,name=sendToSubscriptionAdministrator"`
	// +optional
	SendToSubscriptionCoAdministrator bool `json:"sendToSubscriptionCoAdministrator,omitempty" tf:"send_to_subscription_co_administrator,omitempty" protobuf:"varint,3,opt,name=sendToSubscriptionCoAdministrator"`
}

type MonitorAutoscaleSettingSpecNotificationWebhook struct {
	// +optional
	Properties map[string]string `json:"properties,omitempty" tf:"properties,omitempty" protobuf:"bytes,1,rep,name=properties"`
	ServiceURI string            `json:"serviceURI" tf:"service_uri" protobuf:"bytes,2,opt,name=serviceURI"`
}

type MonitorAutoscaleSettingSpecNotification struct {
	// +optional
	// +kubebuilder:validation:MaxItems=1
	Email []MonitorAutoscaleSettingSpecNotificationEmail `json:"email,omitempty" tf:"email,omitempty" protobuf:"bytes,1,rep,name=email"`
	// +optional
	Webhook []MonitorAutoscaleSettingSpecNotificationWebhook `json:"webhook,omitempty" tf:"webhook,omitempty" protobuf:"bytes,2,rep,name=webhook"`
}

type MonitorAutoscaleSettingSpecProfileCapacity struct {
	Default int64 `json:"default" tf:"default" protobuf:"varint,1,opt,name=default"`
	Maximum int64 `json:"maximum" tf:"maximum" protobuf:"varint,2,opt,name=maximum"`
	Minimum int64 `json:"minimum" tf:"minimum" protobuf:"varint,3,opt,name=minimum"`
}

type MonitorAutoscaleSettingSpecProfileFixedDate struct {
	End   string `json:"end" tf:"end" protobuf:"bytes,1,opt,name=end"`
	Start string `json:"start" tf:"start" protobuf:"bytes,2,opt,name=start"`
	// +optional
	Timezone string `json:"timezone,omitempty" tf:"timezone,omitempty" protobuf:"bytes,3,opt,name=timezone"`
}

type MonitorAutoscaleSettingSpecProfileRecurrence struct {
	Days []string `json:"days" tf:"days" protobuf:"bytes,1,rep,name=days"`
	// +kubebuilder:validation:MaxItems=1
	Hours []int64 `json:"hours" tf:"hours" protobuf:"varint,2,rep,name=hours"`
	// +kubebuilder:validation:MaxItems=1
	Minutes []int64 `json:"minutes" tf:"minutes" protobuf:"varint,3,rep,name=minutes"`
	// +optional
	Timezone string `json:"timezone,omitempty" tf:"timezone,omitempty" protobuf:"bytes,4,opt,name=timezone"`
}

type MonitorAutoscaleSettingSpecProfileRuleMetricTrigger struct {
	MetricName       string  `json:"metricName" tf:"metric_name" protobuf:"bytes,1,opt,name=metricName"`
	MetricResourceID string  `json:"metricResourceID" tf:"metric_resource_id" protobuf:"bytes,2,opt,name=metricResourceID"`
	Operator         string  `json:"operator" tf:"operator" protobuf:"bytes,3,opt,name=operator"`
	Statistic        string  `json:"statistic" tf:"statistic" protobuf:"bytes,4,opt,name=statistic"`
	Threshold        float64 `json:"threshold" tf:"threshold" protobuf:"fixed64,5,opt,name=threshold"`
	TimeAggregation  string  `json:"timeAggregation" tf:"time_aggregation" protobuf:"bytes,6,opt,name=timeAggregation"`
	TimeGrain        string  `json:"timeGrain" tf:"time_grain" protobuf:"bytes,7,opt,name=timeGrain"`
	TimeWindow       string  `json:"timeWindow" tf:"time_window" protobuf:"bytes,8,opt,name=timeWindow"`
}

type MonitorAutoscaleSettingSpecProfileRuleScaleAction struct {
	Cooldown  string `json:"cooldown" tf:"cooldown" protobuf:"bytes,1,opt,name=cooldown"`
	Direction string `json:"direction" tf:"direction" protobuf:"bytes,2,opt,name=direction"`
	Type      string `json:"type" tf:"type" protobuf:"bytes,3,opt,name=type"`
	Value     int64  `json:"value" tf:"value" protobuf:"varint,4,opt,name=value"`
}

type MonitorAutoscaleSettingSpecProfileRule struct {
	// +kubebuilder:validation:MaxItems=1
	MetricTrigger []MonitorAutoscaleSettingSpecProfileRuleMetricTrigger `json:"metricTrigger" tf:"metric_trigger" protobuf:"bytes,1,rep,name=metricTrigger"`
	// +kubebuilder:validation:MaxItems=1
	ScaleAction []MonitorAutoscaleSettingSpecProfileRuleScaleAction `json:"scaleAction" tf:"scale_action" protobuf:"bytes,2,rep,name=scaleAction"`
}

type MonitorAutoscaleSettingSpecProfile struct {
	// +kubebuilder:validation:MaxItems=1
	Capacity []MonitorAutoscaleSettingSpecProfileCapacity `json:"capacity" tf:"capacity" protobuf:"bytes,1,rep,name=capacity"`
	// +optional
	// +kubebuilder:validation:MaxItems=1
	FixedDate []MonitorAutoscaleSettingSpecProfileFixedDate `json:"fixedDate,omitempty" tf:"fixed_date,omitempty" protobuf:"bytes,2,rep,name=fixedDate"`
	Name      string                                        `json:"name" tf:"name" protobuf:"bytes,3,opt,name=name"`
	// +optional
	// +kubebuilder:validation:MaxItems=1
	Recurrence []MonitorAutoscaleSettingSpecProfileRecurrence `json:"recurrence,omitempty" tf:"recurrence,omitempty" protobuf:"bytes,4,rep,name=recurrence"`
	// +optional
	// +kubebuilder:validation:MaxItems=10
	Rule []MonitorAutoscaleSettingSpecProfileRule `json:"rule,omitempty" tf:"rule,omitempty" protobuf:"bytes,5,rep,name=rule"`
}

type MonitorAutoscaleSettingSpec struct {
	ProviderRef core.LocalObjectReference `json:"providerRef" tf:"-" protobuf:"bytes,1,opt,name=providerRef"`

	ID string `json:"id,omitempty" tf:"id,omitempty" protobuf:"bytes,2,opt,name=id"`

	// +optional
	Enabled  bool   `json:"enabled,omitempty" tf:"enabled,omitempty" protobuf:"varint,3,opt,name=enabled"`
	Location string `json:"location" tf:"location" protobuf:"bytes,4,opt,name=location"`
	Name     string `json:"name" tf:"name" protobuf:"bytes,5,opt,name=name"`
	// +optional
	// +kubebuilder:validation:MaxItems=1
	Notification []MonitorAutoscaleSettingSpecNotification `json:"notification,omitempty" tf:"notification,omitempty" protobuf:"bytes,6,rep,name=notification"`
	// +kubebuilder:validation:MaxItems=20
	Profile           []MonitorAutoscaleSettingSpecProfile `json:"profile" tf:"profile" protobuf:"bytes,7,rep,name=profile"`
	ResourceGroupName string                               `json:"resourceGroupName" tf:"resource_group_name" protobuf:"bytes,8,opt,name=resourceGroupName"`
	// +optional
	Tags             map[string]string `json:"tags,omitempty" tf:"tags,omitempty" protobuf:"bytes,9,rep,name=tags"`
	TargetResourceID string            `json:"targetResourceID" tf:"target_resource_id" protobuf:"bytes,10,opt,name=targetResourceID"`
}

type MonitorAutoscaleSettingStatus struct {
	// Resource generation, which is updated on mutation by the API Server.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty" protobuf:"varint,1,opt,name=observedGeneration"`
	// +optional
	Output *MonitorAutoscaleSettingSpec `json:"output,omitempty" protobuf:"bytes,2,opt,name=output"`
	// +optional
	State *base.State `json:"state,omitempty" protobuf:"bytes,3,opt,name=state"`
	// +optional
	Phase base.Phase `json:"phase,omitempty" protobuf:"bytes,4,opt,name=phase,casttype=kubeform.dev/kubeform/apis/base/v1alpha1.Phase"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true

// MonitorAutoscaleSettingList is a list of MonitorAutoscaleSettings
type MonitorAutoscaleSettingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
	// Items is a list of MonitorAutoscaleSetting CRD objects
	Items []MonitorAutoscaleSetting `json:"items,omitempty" protobuf:"bytes,2,rep,name=items"`
}
