/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by Kubeform. DO NOT EDIT.

package v1alpha1

import (
	base "kubeform.dev/kubeform/apis/base/v1alpha1"

	core "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +k8s:openapi-gen=true
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`

type StreamAnalyticsJob struct {
	metav1.TypeMeta   `json:",inline,omitempty"`
	metav1.ObjectMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
	Spec              StreamAnalyticsJobSpec   `json:"spec,omitempty" protobuf:"bytes,2,opt,name=spec"`
	Status            StreamAnalyticsJobStatus `json:"status,omitempty" protobuf:"bytes,3,opt,name=status"`
}

type StreamAnalyticsJobSpec struct {
	ProviderRef core.LocalObjectReference `json:"providerRef" tf:"-" protobuf:"bytes,1,opt,name=providerRef"`

	ID string `json:"id,omitempty" tf:"id,omitempty" protobuf:"bytes,2,opt,name=id"`

	CompatibilityLevel                 string `json:"compatibilityLevel" tf:"compatibility_level" protobuf:"bytes,3,opt,name=compatibilityLevel"`
	DataLocale                         string `json:"dataLocale" tf:"data_locale" protobuf:"bytes,4,opt,name=dataLocale"`
	EventsLateArrivalMaxDelayInSeconds int64  `json:"eventsLateArrivalMaxDelayInSeconds" tf:"events_late_arrival_max_delay_in_seconds" protobuf:"varint,5,opt,name=eventsLateArrivalMaxDelayInSeconds"`
	EventsOutOfOrderMaxDelayInSeconds  int64  `json:"eventsOutOfOrderMaxDelayInSeconds" tf:"events_out_of_order_max_delay_in_seconds" protobuf:"varint,6,opt,name=eventsOutOfOrderMaxDelayInSeconds"`
	EventsOutOfOrderPolicy             string `json:"eventsOutOfOrderPolicy" tf:"events_out_of_order_policy" protobuf:"bytes,7,opt,name=eventsOutOfOrderPolicy"`
	// +optional
	JobID             string `json:"jobID,omitempty" tf:"job_id,omitempty" protobuf:"bytes,8,opt,name=jobID"`
	Location          string `json:"location" tf:"location" protobuf:"bytes,9,opt,name=location"`
	Name              string `json:"name" tf:"name" protobuf:"bytes,10,opt,name=name"`
	OutputErrorPolicy string `json:"outputErrorPolicy" tf:"output_error_policy" protobuf:"bytes,11,opt,name=outputErrorPolicy"`
	ResourceGroupName string `json:"resourceGroupName" tf:"resource_group_name" protobuf:"bytes,12,opt,name=resourceGroupName"`
	StreamingUnits    int64  `json:"streamingUnits" tf:"streaming_units" protobuf:"varint,13,opt,name=streamingUnits"`
	// +optional
	Tags                map[string]string `json:"tags,omitempty" tf:"tags,omitempty" protobuf:"bytes,14,rep,name=tags"`
	TransformationQuery string            `json:"transformationQuery" tf:"transformation_query" protobuf:"bytes,15,opt,name=transformationQuery"`
}

type StreamAnalyticsJobStatus struct {
	// Resource generation, which is updated on mutation by the API Server.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty" protobuf:"varint,1,opt,name=observedGeneration"`
	// +optional
	Output *StreamAnalyticsJobSpec `json:"output,omitempty" protobuf:"bytes,2,opt,name=output"`
	// +optional
	State *base.State `json:"state,omitempty" protobuf:"bytes,3,opt,name=state"`
	// +optional
	Phase base.Phase `json:"phase,omitempty" protobuf:"bytes,4,opt,name=phase,casttype=kubeform.dev/kubeform/apis/base/v1alpha1.Phase"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true

// StreamAnalyticsJobList is a list of StreamAnalyticsJobs
type StreamAnalyticsJobList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
	// Items is a list of StreamAnalyticsJob CRD objects
	Items []StreamAnalyticsJob `json:"items,omitempty" protobuf:"bytes,2,rep,name=items"`
}
