/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by Kubeform. DO NOT EDIT.

package v1alpha1

import (
	base "kubeform.dev/kubeform/apis/base/v1alpha1"

	core "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +k8s:openapi-gen=true
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`

type Volume struct {
	metav1.TypeMeta   `json:",inline,omitempty"`
	metav1.ObjectMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
	Spec              VolumeSpec   `json:"spec,omitempty" protobuf:"bytes,2,opt,name=spec"`
	Status            VolumeStatus `json:"status,omitempty" protobuf:"bytes,3,opt,name=status"`
}

type VolumeSpec struct {
	ProviderRef core.LocalObjectReference `json:"providerRef" tf:"-" protobuf:"bytes,1,opt,name=providerRef"`

	ID string `json:"id,omitempty" tf:"id,omitempty" protobuf:"bytes,2,opt,name=id"`

	// +optional
	Description string `json:"description,omitempty" tf:"description,omitempty" protobuf:"bytes,3,opt,name=description"`
	// +optional
	DropletIDS []int64 `json:"dropletIDS,omitempty" tf:"droplet_ids,omitempty" protobuf:"varint,4,rep,name=dropletIDS"`
	// +optional
	FilesystemLabel string `json:"filesystemLabel,omitempty" tf:"filesystem_label,omitempty" protobuf:"bytes,5,opt,name=filesystemLabel"`
	// +optional
	// Deprecated
	FilesystemType string `json:"filesystemType,omitempty" tf:"filesystem_type,omitempty" protobuf:"bytes,6,opt,name=filesystemType"`
	// +optional
	InitialFilesystemLabel string `json:"initialFilesystemLabel,omitempty" tf:"initial_filesystem_label,omitempty" protobuf:"bytes,7,opt,name=initialFilesystemLabel"`
	// +optional
	InitialFilesystemType string `json:"initialFilesystemType,omitempty" tf:"initial_filesystem_type,omitempty" protobuf:"bytes,8,opt,name=initialFilesystemType"`
	Name                  string `json:"name" tf:"name" protobuf:"bytes,9,opt,name=name"`
	Region                string `json:"region" tf:"region" protobuf:"bytes,10,opt,name=region"`
	Size                  int64  `json:"size" tf:"size"`
	// +optional
	SnapshotID string `json:"snapshotID,omitempty" tf:"snapshot_id,omitempty" protobuf:"bytes,12,opt,name=snapshotID"`
	// the uniform resource name for the volume.
	// +optional
	Urn string `json:"urn,omitempty" tf:"urn,omitempty" protobuf:"bytes,13,opt,name=urn"`
}

type VolumeStatus struct {
	// Resource generation, which is updated on mutation by the API Server.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty" protobuf:"varint,1,opt,name=observedGeneration"`
	// +optional
	Output *VolumeSpec `json:"output,omitempty" protobuf:"bytes,2,opt,name=output"`
	// +optional
	State *base.State `json:"state,omitempty" protobuf:"bytes,3,opt,name=state"`
	// +optional
	Phase base.Phase `json:"phase,omitempty" protobuf:"bytes,4,opt,name=phase,casttype=kubeform.dev/kubeform/apis/base/v1alpha1.Phase"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true

// VolumeList is a list of Volumes
type VolumeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
	// Items is a list of Volume CRD objects
	Items []Volume `json:"items,omitempty" protobuf:"bytes,2,rep,name=items"`
}
