/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by Kubeform. DO NOT EDIT.

package v1alpha1

import (
	base "kubeform.dev/kubeform/apis/base/v1alpha1"

	core "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +k8s:openapi-gen=true
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`

type CloudfunctionsFunction struct {
	metav1.TypeMeta   `json:",inline,omitempty"`
	metav1.ObjectMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
	Spec              CloudfunctionsFunctionSpec   `json:"spec,omitempty" protobuf:"bytes,2,opt,name=spec"`
	Status            CloudfunctionsFunctionStatus `json:"status,omitempty" protobuf:"bytes,3,opt,name=status"`
}

type CloudfunctionsFunctionSpecEventTriggerFailurePolicy struct {
	Retry bool `json:"retry" tf:"retry" protobuf:"varint,1,opt,name=retry"`
}

type CloudfunctionsFunctionSpecEventTrigger struct {
	EventType string `json:"eventType" tf:"event_type" protobuf:"bytes,1,opt,name=eventType"`
	// +optional
	// +kubebuilder:validation:MaxItems=1
	FailurePolicy []CloudfunctionsFunctionSpecEventTriggerFailurePolicy `json:"failurePolicy,omitempty" tf:"failure_policy,omitempty" protobuf:"bytes,2,rep,name=failurePolicy"`
	Resource      string                                                `json:"resource" tf:"resource" protobuf:"bytes,3,opt,name=resource"`
}

type CloudfunctionsFunctionSpec struct {
	ProviderRef core.LocalObjectReference `json:"providerRef" tf:"-" protobuf:"bytes,1,opt,name=providerRef"`

	ID string `json:"id,omitempty" tf:"id,omitempty" protobuf:"bytes,2,opt,name=id"`

	// +optional
	AvailableMemoryMb int64 `json:"availableMemoryMb,omitempty" tf:"available_memory_mb,omitempty" protobuf:"varint,3,opt,name=availableMemoryMb"`
	// +optional
	Description string `json:"description,omitempty" tf:"description,omitempty" protobuf:"bytes,4,opt,name=description"`
	// +optional
	EntryPoint string `json:"entryPoint,omitempty" tf:"entry_point,omitempty" protobuf:"bytes,5,opt,name=entryPoint"`
	// +optional
	EnvironmentVariables map[string]string `json:"environmentVariables,omitempty" tf:"environment_variables,omitempty" protobuf:"bytes,6,rep,name=environmentVariables"`
	// +optional
	// +kubebuilder:validation:MaxItems=1
	EventTrigger []CloudfunctionsFunctionSpecEventTrigger `json:"eventTrigger,omitempty" tf:"event_trigger,omitempty" protobuf:"bytes,7,rep,name=eventTrigger"`
	// +optional
	HttpsTriggerURL string `json:"httpsTriggerURL,omitempty" tf:"https_trigger_url,omitempty" protobuf:"bytes,8,opt,name=httpsTriggerURL"`
	// +optional
	Labels map[string]string `json:"labels,omitempty" tf:"labels,omitempty" protobuf:"bytes,9,rep,name=labels"`
	Name   string            `json:"name" tf:"name" protobuf:"bytes,10,opt,name=name"`
	// +optional
	Project string `json:"project,omitempty" tf:"project,omitempty" protobuf:"bytes,11,opt,name=project"`
	// +optional
	Region string `json:"region,omitempty" tf:"region,omitempty" protobuf:"bytes,12,opt,name=region"`
	// +optional
	// Deprecated
	RetryOnFailure bool `json:"retryOnFailure,omitempty" tf:"retry_on_failure,omitempty" protobuf:"varint,13,opt,name=retryOnFailure"`
	// +optional
	Runtime             string `json:"runtime,omitempty" tf:"runtime,omitempty" protobuf:"bytes,14,opt,name=runtime"`
	SourceArchiveBucket string `json:"sourceArchiveBucket" tf:"source_archive_bucket" protobuf:"bytes,15,opt,name=sourceArchiveBucket"`
	SourceArchiveObject string `json:"sourceArchiveObject" tf:"source_archive_object" protobuf:"bytes,16,opt,name=sourceArchiveObject"`
	// +optional
	Timeout int64 `json:"timeout,omitempty" tf:"timeout,omitempty" protobuf:"varint,17,opt,name=timeout"`
	// +optional
	// Deprecated
	TriggerBucket string `json:"triggerBucket,omitempty" tf:"trigger_bucket,omitempty" protobuf:"bytes,18,opt,name=triggerBucket"`
	// +optional
	TriggerHTTP bool `json:"triggerHTTP,omitempty" tf:"trigger_http,omitempty" protobuf:"varint,19,opt,name=triggerHTTP"`
	// +optional
	// Deprecated
	TriggerTopic string `json:"triggerTopic,omitempty" tf:"trigger_topic,omitempty" protobuf:"bytes,20,opt,name=triggerTopic"`
}

type CloudfunctionsFunctionStatus struct {
	// Resource generation, which is updated on mutation by the API Server.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty" protobuf:"varint,1,opt,name=observedGeneration"`
	// +optional
	Output *CloudfunctionsFunctionSpec `json:"output,omitempty" protobuf:"bytes,2,opt,name=output"`
	// +optional
	State *base.State `json:"state,omitempty" protobuf:"bytes,3,opt,name=state"`
	// +optional
	Phase base.Phase `json:"phase,omitempty" protobuf:"bytes,4,opt,name=phase,casttype=kubeform.dev/kubeform/apis/base/v1alpha1.Phase"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true

// CloudfunctionsFunctionList is a list of CloudfunctionsFunctions
type CloudfunctionsFunctionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
	// Items is a list of CloudfunctionsFunction CRD objects
	Items []CloudfunctionsFunction `json:"items,omitempty" protobuf:"bytes,2,rep,name=items"`
}
